### PR TITLE
Add fuzzing infrastructure and fix some issues found with it

### LINKED ISSUE #37: Consider fuzzing the crate.
This would help improve test coverage and find potential  issues.

### PR DESCRIPTION
**Pull request by JCapucho**
Adds fuzzing using [afl.rs](https://github.com/rust-fuzz/afl.rs) and fixes some errors found by it

- If parser performing operation without checking for overflows and division by zero
- The `ReplaceComment` lexer could cause stack overflows with larger inputs

### CODE REVIEW

**Comment by JCapucho** [comment]
I also found a stack overflow in the if parser, I will fix it in a separate PR

File: src/lexer.rs [hunk 1]
```diff
@@ -137,50 +137,50 @@ impl<'a> Iterator for ReplaceComments<'a> {
...
         let mut current = self.inner.next()?;
 
-        if current.0 != '/' {
-            debug_assert!(current.0 != COMMENT_SENTINEL_VALUE);
-            return Some(current);
-        }
-
-        let mut save_point = self.inner.clone();
-        match self.next() {
+        match current {
```
Comment (Kangz) [inline src/lexer.rs]: nit: The previous version doing the early out on non-/ chars was a bit easier to read because of the reduced indentation level, and I think it is unrelated to the stack overflow issue.

**Review by Kangz — APPROVED** [review]

File: src/lexer.rs (hunk 1 above)
Comment (JCapucho) [reply src/lexer.rs]: I also think it was related to the save_point and the recursive call to next.

I'll change it as soon as I can to use an if for early return.

**Comment by JCapucho** [comment]
@Kangz Fixed the nit you pointed out, also I tried to check out the stack overflow in the if parser but I don't see how it can be fixed since it would require us to remove all recursion from the parser and since it only happens with thousands of nested operations (like for example applying the not operator hundreds of times for a single number) I don't think it's really worth it to look deeper into it.

**Comment by Kangz** [comment]
Yeah the overflow in the if parser would be difficult to fix, and would require a complete rewrite with an explicit stack. I don't think we need to go there yet (until/if this create is used in a security sensitive environment). Thanks for fixing the nit, still LGTM! You should be able to merge yourself.

**Comment by Kangz** [comment]
Actually I'll merge now since I need to rebase a WIP PR on it.
